"""create feature tables

Revision ID: cdc0e66c9b96
Revises: 
Create Date: 2026-03-11 12:41:54.635979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc0e66c9b96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_name'), ['name'], unique=True)

    op.create_table('feature_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feature_id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_rules_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_rules_rule_type'), ['rule_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_rules_rule_type'))
        batch_op.drop_index(batch_op.f('ix_feature_rules_feature_id'))

    op.drop_table('feature_rules')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_name'))

    op.drop_table('features')
    # ### end Alembic commands ###
